package com.stotrakosh.stotrakoshbackend;

        import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.stereotype.Controller;
        import org.springframework.web.bind.annotation.GetMapping;
        import org.springframework.web.bind.annotation.PostMapping;
        import org.springframework.web.bind.annotation.RequestMapping;
        import org.springframework.web.bind.annotation.RequestParam;
        import org.springframework.web.bind.annotation.ResponseBody;

        import java.util.stream.Collectors;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/stotrakosh") // This means URL's start with /demo (after Application path)
public class StotrakoshController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StotrakoshRepository stotrakoshRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Stotrakosh> getAllStotrakoshs() {
        // This returns a JSON or XML with the users
        Iterable<Stotrakosh> allStotrakosh = stotrakoshRepository.findAll();
        return allStotrakosh;
    }
}
