package com.stotrakosh.stotrakoshbackend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/stotrakosh")//, method = {RequestMethod.GET, RequestMethod.POST}) // This means URL's start with /demo (after Application path)
@CrossOrigin(origins = {"http://localhost:4200/", "http://localhost:8080/"}, methods = {RequestMethod.GET, RequestMethod.POST})
public class StotrakoshController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StotrakoshRepository stotrakoshRepository;
    private Transliteration transliteration;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Stotrakosh> getAllStotrakoshs() {
        // This returns a JSON or XML with the users
        Iterable<Stotrakosh> allStotrakosh = stotrakoshRepository.findAll();
        return allStotrakosh;
    }
}
